// Code generated by gobind. DO NOT EDIT.

// Java class gliderandroid.MyConn is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/doorbash/glider-android
package gliderandroid;

import go.Seq;

public final class MyConn implements Seq.Proxy, MyConnI {
	static { Gliderandroid.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	MyConn(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public MyConn() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void close() throws Exception;
	public native String localAddr();
	public native long read(byte[] b) throws Exception;
	public native long readOffLen(byte[] b, long off, long len) throws Exception;
	public native String remoteAddr();
	public native void setReadTimeout(long timeout) throws Exception;
	public native void setTimeout(long timeout) throws Exception;
	public native void setWriteTimeout(long timeout) throws Exception;
	public native long write(byte[] b) throws Exception;
	public native long writeOffLen(byte[] b, long off, long len) throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof MyConn)) {
		    return false;
		}
		MyConn that = (MyConn)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("MyConn").append("{");
		return b.append("}").toString();
	}
}

