// Code generated by gobind. DO NOT EDIT.

// Java class gliderandroid.MyUDPConn is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/doorbash/glider-android
package gliderandroid;

import go.Seq;

public final class MyUDPConn implements Seq.Proxy {
	static { Gliderandroid.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	MyUDPConn(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public MyUDPConn() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field MyUDPConn.PacketConn with unsupported type: net.PacketConn
	
	public native void close() throws Exception;
	// skipped method MyUDPConn.LocalAddr with unsupported parameter or return types
	
	public native long read(byte[] b) throws Exception;
	// skipped method MyUDPConn.ReadFrom with unsupported parameter or return types
	
	// skipped method MyUDPConn.RemoteAddr with unsupported parameter or return types
	
	// skipped method MyUDPConn.SetDeadline with unsupported parameter or return types
	
	// skipped method MyUDPConn.SetReadDeadline with unsupported parameter or return types
	
	// skipped method MyUDPConn.SetWriteDeadline with unsupported parameter or return types
	
	public native long write(byte[] b) throws Exception;
	// skipped method MyUDPConn.WriteTo with unsupported parameter or return types
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof MyUDPConn)) {
		    return false;
		}
		MyUDPConn that = (MyUDPConn)o;
		// skipped field MyUDPConn.PacketConn with unsupported type: net.PacketConn
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("MyUDPConn").append("{");
		return b.append("}").toString();
	}
}

