// Code generated by gobind. DO NOT EDIT.

// Java class gliderandroid.StringCollection is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/doorbash/glider-android
package gliderandroid;

import go.Seq;

public interface StringCollection {
	public StringCollection add(String s);
	public String get(long i);
	public long size();
	
}

